# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "ultra4987309647secret!key"  # change this!
  limiter: false  # enable this when running the instance for a public usage on the internet
  image_proxy: true
valkey:
  url: valkey://valkey:6379/0
engines:
  - name: ahmia
    inactive: true
  - name: torch
    inactive: true
